# config.py
API_KEY = 'WdnsWy1lELmRU8BhoaaDviZEiUedohy6JxiUxiRcsAYJ1jKt2eXW1fQUvXj4ISWQ'
SECRET_KEY = 'o3xRToTzSF2eTaCuPh6tCjliPYebQmnWXbs5784QY3qFmnperHBcQOzRt937ZQHy'
TIMEFRAME = '15m'
SINCE_PERIOD = '4 days ago UTC'
RSI_THRESHOLD = 28
STOCH_RSI_THRESHOLD = 20
LOOKBACK_PERIOD = 96
SELL_RSI_THRESHOLD = 70
LOSS_THRESHOLD = 0.03
HOLD_TIME = 60
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'XRP/USDT']
TRADE_AMOUNT_MODE = 'percentage'
FIXED_USDT_AMOUNT = 100
TRADE_PERCENTAGE = 0.05
DB_FILE = 'trades.db'
