# config.py
API_KEY = 'XXX'
SECRET_KEY = 'XXX'
TIMEFRAME = '15m'
SINCE_PERIOD = '4 days ago UTC'
LOOKBACK_PERIOD = 96  # Lookback period in terms of number of candlesticks
RSI_THRESHOLD = 28
STOCH_RSI_THRESHOLD = 20
LOOKBACK_PERIOD = 96
SELL_RSI_THRESHOLD = 70
LOSS_THRESHOLD = 0.03
HOLD_TIME = 60
SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'XRP/USDT']
TRADE_AMOUNT_MODE = 'percentage'
FIXED_USDT_AMOUNT = 100
TRADE_PERCENTAGE = 0.05
DB_FILE = 'trades.db'
